version: '3'

volumes:
  eosio-data:
    external:
      name: eosio-data

services:
  eosio:
    build:
      context: ./blockchain
    container_name: "eosio"
    ports:
      - 8888:8888
    volumes:
      - ./:/var/repo
      - eosio-data:/data
  tonomy-id-demo:
    image: node:16.4.1-slim
    container_name: "tonomy-id-demo"
    ports:
      - 3000:3000
    environment:
      # makes webpack work with docker-compose
      - WATCHPACK_POLLING=true
    user: "root"
    volumes:
      - ./:/var/repo
    working_dir: /var/repo/Tonomy-ID-Demo
    command: npm start
