version: '3'

volumes:
  antelope-data:
    external:
      name: antelope-data

services:
  antelope:
    image: tonomy_blockchain_initialized
    container_name: "antelope"
    ports:
      - 8888:8888
    volumes:
      - antelope-data:/data
