version: '3'

volumes:
  eosio-data:
    external:
      name: eosio-data

services:
  eosio:
    build:
      context: ./blockchain
    container_name: "eosio"
    ports:
      - 8888:8888
    volumes:
      - ./:/var/repo
      - eosio-data:/data

  demo:
    image: node:16.4.1
    container_name: "demo"
    ports:
      - 3000:3000
    volumes:
      - ./:/var/repo
    working_dir: /var/repo/Tonomy-ID-Demo
    command: [ "npm", "run", "start" ]
