version: '3'
services:
  eosio:
    build:
      context: ./blockchain
      dockerfile: Dockerfile-eosio
    container_name: "eosio"
    ports:
      - 8888:8888
    volumes:
      - ./:/var/repo
      - ./temp/eosio:/data
