version: '3'

volumes:
  eosio-data:
    external:
      name: eosio-data

services:
  eosio:
    build:
      context: ./blockchain
    container_name: "eosio"
    ports:
      - 8888:8888
    volumes:
      - ./:/var/repo
      - eosio-data:/data
  nginx:
    image: nginx:1.23.1
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf