# Adapted from https://github.com/ccarcaci/andocker/blob/master/ecosystem/Dockerfile-expo
FROM node:16.4.1

USER root
RUN apt update
RUN apt install zip apt-utils -y

# Install Java JDK 11
RUN apt install openjdk-11-jdk -y

WORKDIR /home/node

# Installs Android SDK
# adapted from https://stackoverflow.com/questions/68539423/running-android-emulator-in-docker-container
ENV ANDROID_HOME=/android-sdk
ENV ANDROID_SDK_HOME $ANDROID_HOME

# See https://developer.android.com/studio/#command-tools
ARG ANDROID_SDK_VERSION=8512546
# See https://developer.android.com/studio/releases/platforms (react native requires minimum API level 30)
ARG ANDROID_BUILD_TOOLS_VERSION=30.0.0
ARG ANDROID_PLATFORM_VERSION="android-30"

USER root
RUN mkdir -p ${ANDROID_SDK_HOME}
RUN chown node ${ANDROID_SDK_HOME}

USER node
RUN wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_VERSION}_latest.zip
RUN unzip *tools*linux*.zip -d ${ANDROID_SDK_HOME}
RUN rm *tools*linux*.zip

ENV PATH ${PATH}:${ANDROID_SDK_HOME}/tools:${ANDROID_SDK_HOME}/platform-tools

RUN mkdir -p ~/.android
RUN touch ~/.android/repositories.cfg
RUN echo y | ${ANDROID_SDK_HOME}/cmdline-tools/bin/sdkmanager --licenses --sdk_root=${ANDROID_SDK_HOME}
RUN echo y | ${ANDROID_SDK_HOME}/cmdline-tools/bin/sdkmanager "platform-tools" --sdk_root=${ANDROID_SDK_HOME}
RUN echo y | ${ANDROID_SDK_HOME}/cmdline-tools/bin/sdkmanager "build-tools;$ANDROID_BUILD_TOOLS_VERSION" --sdk_root=${ANDROID_SDK_HOME}
RUN echo y | ${ANDROID_SDK_HOME}/cmdline-tools/bin/sdkmanager "platforms;$ANDROID_PLATFORM_VERSION" --sdk_root=${ANDROID_SDK_HOME}

# Install dockerize
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/${DOCKERIZE_VERSION}/dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz
RUN tar -xzvf dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz
RUN rm dockerize-linux-amd64-${DOCKERIZE_VERSION}.tar.gz