#!/bin/bash

function help {
    echo ""
    echo "Usage:"
    echo "    app.sh [commands]"
    echo ""
    echo "Commands:"
    echo "    gitinit [master] - initializes all git submodules and checks out development (or master) branch"
    echo "    install [master] - installs all application repositories"
    echo "    update [master]  - updates all client's with latest publish @tonomy/tonomy-id-sdk repository"
    echo "    link             - links all repositories together with npm/yarn link command, useful for debugging"
    echo "    init             - starts application components through docker compose and initializes and resets the blockchain and database"
    echo "    start            - starts all application components (need to run init first)"
    echo "    stop             - stops application execution"
    echo "    test             - runs all automated tests"
    echo "    reset [all]      - stops application execution and resets all data. Optionally specify 'all' to also reset all node_modules"
    echo "    log [service]    - prints logs for the service"
}

function loghelp {
    echo ""
    echo "Prints out last 10 lines of logs for the service"
    echo ""
    echo "Usage:"
    echo "    app.sh log [commands]"
    echo ""
    echo "Commands:"
    echo "    antelope - blockchain node (antelope)"
    echo "    sdk      - Tonomy ID SDK (tsdx)"
    echo "    id       - Tonomy ID app expo packaer (react native)"
    echo "    apps      - Tonomy ID SSO app  & Tonomy ID DEMO MARKET (react)"
    echo "    micro   - Tonomy Communication microservice (nestjs)"
}

function printservices {
    echo "##################################################"
    echo ""
    echo ""
    echo ""
    echo "Services now running:"
    echo ""
    echo "Tonomy ID expo package (metro)    - http://${ip}:8081"
    echo "Tonomy ID app debugger            - http://localhost:8081/debugger-ui/"
    echo "Blockchain node (Antelope)        - http://localhost:8888/v1/chain/get_info"
    echo "Blockchain explorer               - https://local.bloks.io/?nodeUrl=http%3A%2F%2Flocalhost%3A8888&coreSymbol=SYS&systemDomain=eosio"
    echo "Tonomy ID Accounts App (react)    - http://${ip}:3000 "
    echo "Tonomy ID Demo App (react)        - http://${ip}:3001"
    echo "Tonomy Communication microservice - http://${ip}:5000"
    echo ""
    echo ""
    echo "Your IP = ${ip}"
    echo ""
    echo ""
}